server:
  port: 8000

spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:sqlserver://127.0.0.1:1433;databaseName=typdb;encrypt=false;trustServerCertificate=true
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          username: sa
          password: Jxadmin?

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


