spring:
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
          max-tokens: 2000

# LangChain4j Configuration
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
      model-name: gpt-3.5-turbo
      temperature: 0.7
      max-tokens: 2000
    embedding-model:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
      model-name: text-embedding-ada-002

# Report Generation Configuration
report:
  templates:
    path: classpath:templates/reports/
  output:
    path: ./reports/
    format: pdf,html,json
  cache:
    enabled: true
    ttl: 3600 # 1 hour

logging:
  level:
    dev.langchain4j: DEBUG
    com.typ.ai: DEBUG
